export const styles = {
  globalnav: {
    width: "100%",
    height: { xs: "48px", md: "44px" },
    backgroundColor: "primary.secondary",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "12px",
    boxSizing: "border-box",
  },
  globalnavItmes: {
    overflow: "hidden",
    width: "996px",
    height: "100%",
    display: "flex",
    justifyContent: "space-between",
    color: "primary.warning",
    padding: "0 0",
    fontFamily: "Helvetica Neue , Arial ,Apple Color Emoji ",
    alignItems: "center",
    margin: "0",
  },
  chapternav: {
    boxSizing: "border-box",
    margin: "8px 0  0 8px ",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    overflow: "scroll",
    backgroundColor: "white",
  },
  chapternavItems: {
    TextAlign: "center",
    height: "100px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  ribbonContentWrapper: {
    width: "100%",
    backgroundColor: "primary.light",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
};
