export const FooterText = [
    {
        footnote1: "",
        footnote2: "",
        footnote3: "",
        footnote4: "",
        footnote5: "",
        footnote6: "",
        footnote7: "",
        footnote8: "",
        footnote9: "",
        footnote10: "",
        footnote11: "",
        footnote12: "",
        footnote13: "",
        footnote14: "",
        footnote15: "",
        footnote16: "",
        footnote17: "",
        footnote18: "",
        footnote19: "",
        breadcrumbs: "",
        directory: [
            {
                title: "Shop and Learn 
                ",
                linkS: "Store",
                linkM: "Mac",
                linki: "iPad",
                linkI: "iphone",
                linkW: "Watch",
                linkA: "AirPods",
                linkT: "TV & Home",
                linkAT: "AirTag",
                linkAcc: "Accessories",
                linkG: "Gift Cards",
            },
            {
                title: "Services",
                link1: "Apple Music",
                link2: "Apple TV+",
                link3: "Apple Fitness+",
                link4: "Apple News+",
                link5: "Apple Arcade",
                link6: "iCould",
                link7: "Apple One",
                link8: "Apple Card",
                link9: "Apple Books",
                link10: "Apple Podcasts",
                link11: "App Store",
                title1: "Account",
                linK1: "Manage Your Apple ID",
                linK2: "Apple Store Account",
                linK3: "iCould.com",
            },
            {
                title: "Apple Store",
                link1: "Find a Store",
                link2: "Genius Bar",
                link3: "Today at Apple",
                link4: "Apple Camp",
                link5: "Apple Store App",
                link6: "Refurbished and Clearance",
                link7: "Financing",
                link8: "Apple Trade In",
                link9: "Order Status",
                link10: "Shopping Help",
            },
            {
                title: "For Business",
                link1: "Apple and Business",
                link2: "Shop for Business",
                title1: "For Education",
                link3: "",
                link4: "",
                link5: "",
                link6: "",
                link7: "",
                link8: "",
                link9: "",
                link10: "",
            },
            {
                title: "Apple Values",
                link1: "Find a Store",
                link2: "",
                link3: "",
                link4: "",
                link5: "",
                link6: "",
                link7: "",
                link8: "",
                link9: "",
                link10: "",
            },
        ]
    }
]